// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://drgzzdbffuihtomeswfg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRyZ3p6ZGJmZnVpaHRvbWVzd2ZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1MTY5NjAsImV4cCI6MjA2NjA5Mjk2MH0.YL8jbt7ilqMkP6kHM9lqpxpsFk7abjM8ccCIia0mtT8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);